# [SEED]
manual_seed: 2024
eval_clip: False

# [NETWORKS]
clip_name: RN50
latent_dim: 1024        # Keep the same with your training configuration
out_dim: 1024           # Keep the same with your training configuration
repeat: 0              # Keep the same with your training configuration
scale: 0.056           # alpha value of the disentangled network for inference
activation: torch.nn.SiLU  

# [model to be evaluated] 
which_network: 
  - beta                                   # CLAP, keep the same with your training configuration.
ckpt_path: runs/Sep09_15-40-19_tianjiao-MS-7D67     # Path to your checkpoints path of your trained disentangled network
                                           # If `eval_clip: True`, specify a directory to save the evaluation results.

# [EVAL DATASETS]
eval_sets: [caltech-101]
